[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aors = "0.3.1"
fancy-regex = "0.12.0"
hashbrown = "0.14.2"
itertools = "0.12.0"
memoize = "0.4.1"
serde_json = "1.0.108"
